const SurvivalState = require('./SurvivalState');

/**
 * SurvivalPriorityEngine
 * Evaluates SurvivalState to determine the highest priority survival goal.
 */
class SurvivalPriorityEngine {
  static GOALS = Object.freeze({
    ESCAPE_DANGER: 'ESCAPE_DANGER',
    RECOVER_HEALTH: 'RECOVER_HEALTH',
    EAT: 'EAT',
    FIND_SAFETY: 'FIND_SAFETY',
    PREPARE_FOR_NIGHT: 'PREPARE_FOR_NIGHT',
    FIND_FOOD: 'FIND_FOOD',
    CRAFT_BASIC_TOOLS: 'CRAFT_BASIC_TOOLS',
    GATHER_WOOD: 'GATHER_WOOD',
    GATHER_STONE: 'GATHER_STONE',
    USER_TASK: 'USER_TASK'
  });

  /**
   * Evaluate what the bot should do next based on survival priorities.
   * @param {object} survivalState Generated by SurvivalState.evaluate
   * @param {object} currentTask The current active task (to determine if we should interrupt)
   * @returns {object} { goal, priority, reason }
   */
  static evaluate(survivalState, currentTask = null) {
    if (!survivalState) return { goal: this.GOALS.USER_TASK, priority: 0, reason: 'No state' };

    const priorities = [];

    // 1. Critical Danger (Immediate threat)
    if (survivalState.danger.level === 'CRITICAL' || survivalState.danger.level === 'HIGH') {
      priorities.push({
        goal: this.GOALS.ESCAPE_DANGER,
        priority: 100,
        reason: `Immediate danger detected (${survivalState.danger.level}): ${survivalState.danger.reasons.join(', ')}`
      });
    } else if (survivalState.danger.level === 'MEDIUM' && survivalState.time.isNight) {
      priorities.push({
        goal: this.GOALS.FIND_SAFETY,
        priority: 95,
        reason: 'Hostile mobs nearby at night'
      });
    }

    // 2. Critical Health
    if (survivalState.health.ratio <= 0.3) {
      priorities.push({
        goal: this.GOALS.RECOVER_HEALTH,
        priority: 90,
        reason: `Critical health (${survivalState.health.current}/${survivalState.health.max})`
      });
    } else if (survivalState.health.ratio <= 0.6) {
      priorities.push({
        goal: this.GOALS.RECOVER_HEALTH,
        priority: 70,
        reason: `Low health (${survivalState.health.current}/${survivalState.health.max})`
      });
    }

    // 3. Hunger
    if (survivalState.food.ratio <= 0.3) { // 6 or less (can't sprint)
      if (survivalState.inventory.hasFood) {
        priorities.push({
          goal: this.GOALS.EAT,
          priority: 85,
          reason: `Critical hunger (${survivalState.food.current}/20), eating available food`
        });
      } else {
        priorities.push({
          goal: this.GOALS.FIND_FOOD,
          priority: 85,
          reason: `Critical hunger (${survivalState.food.current}/20) and no food in inventory`
        });
      }
    } else if (survivalState.food.ratio <= 0.7) {
      if (survivalState.inventory.hasFood) {
        priorities.push({
          goal: this.GOALS.EAT,
          priority: 60,
          reason: `Hungry (${survivalState.food.current}/20)`
        });
      } else {
        priorities.push({
          goal: this.GOALS.FIND_FOOD,
          priority: 50,
          reason: 'Low food inventory and getting hungry'
        });
      }
    }

    // 4. Night Preparation / Safety
    if (survivalState.time.isNight && survivalState.danger.level !== 'NONE') {
      priorities.push({
        goal: this.GOALS.FIND_SAFETY,
        priority: 75,
        reason: 'Nighttime with potential danger'
      });
    } else if (survivalState.time.isNight && !survivalState.time.isDay) {
       priorities.push({
        goal: this.GOALS.PREPARE_FOR_NIGHT,
        priority: 40,
        reason: 'Nighttime approaching or active'
      });
    }

    // 5. Basic Needs (Tools / Wood)
    if (!survivalState.inventory.hasWood && !survivalState.equipment.hasAxe && !survivalState.equipment.hasPickaxe) {
      priorities.push({
        goal: this.GOALS.GATHER_WOOD,
        priority: 35,
        reason: 'No basic resources (wood) or tools available'
      });
    } else if (survivalState.inventory.hasWood && !survivalState.equipment.hasPickaxe) {
      priorities.push({
        goal: this.GOALS.CRAFT_BASIC_TOOLS,
        priority: 30,
        reason: 'Have wood, need basic tools'
      });
    } else if (survivalState.equipment.hasPickaxe && !survivalState.inventory.hasStone) {
      priorities.push({
        goal: this.GOALS.GATHER_STONE,
        priority: 25,
        reason: 'Have tools, need stone for upgrades'
      });
    }

    // 6. User Task (Default fallback)
    let userTaskPriority = 20; // Default base priority for user task
    if (currentTask && currentTask.metadata && currentTask.metadata.priority) {
      // If task has explicit priority, use it, but cap it so it doesn't override critical survival
      userTaskPriority = Math.min(80, currentTask.metadata.priority);
    }
    
    priorities.push({
      goal: this.GOALS.USER_TASK,
      priority: userTaskPriority,
      reason: currentTask ? `Continue user task: ${currentTask.name}` : 'No immediate survival needs, ready for task'
    });

    // Sort by priority descending
    priorities.sort((a, b) => b.priority - a.priority);

    return priorities[0];
  }

  /**
   * Evaluate all priorities
   * @param {object} survivalState 
   * @param {object} currentTask 
   * @returns {Array<object>}
   */
  static getPriorities(survivalState, currentTask = null) {
    if (!survivalState) return [];
    
    const highest = this.evaluate(survivalState, currentTask);
    
    // Calculate a list of all priorities for UI display
    // We basically just run evaluate without the final `[0]` slice, but let's do a simplified version
    // since evaluate() already builds the array, we can just refactor it if we want.
    // For now, let's just use the logic from evaluate.
    
    const priorities = [];
    // ... we can just duplicate or extract the logic.
    // Let's refactor:
    
    if (survivalState.danger.level === 'CRITICAL' || survivalState.danger.level === 'HIGH') {
      priorities.push({ goal: this.GOALS.ESCAPE_DANGER, priority: 100 });
    }
    if (survivalState.health.ratio <= 0.3) {
      priorities.push({ goal: this.GOALS.RECOVER_HEALTH, priority: 90 });
    }
    if (survivalState.food.ratio <= 0.3) {
      priorities.push({ goal: survivalState.inventory.hasFood ? this.GOALS.EAT : this.GOALS.FIND_FOOD, priority: 85 });
    }
    
    priorities.push({ goal: this.GOALS.USER_TASK, priority: 20 });
    
    priorities.push(highest);
    
    // deduplicate
    const unique = [];
    const seen = new Set();
    for (const p of priorities) {
      if (!seen.has(p.goal)) {
        seen.add(p.goal);
        unique.push(p);
      }
    }
    
    return unique.sort((a, b) => b.priority - a.priority);
  }
}

module.exports = SurvivalPriorityEngine;
